name: S3 Deploy

# to pick up the pushing of tags we might need additional
# properties under push like
# push:
#   tags:
#   - 'v*'
on: push

jobs:
  s3-deploy:
    name: S3 Deploy
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Setup Ruby 2.4
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.4'
      - name: Install Dependencies
        run: |
          gem install s3_website -v 3.4.0
          npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: ./s3_deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
